name: flutter_session
description: Adds session support to Flutter. Works with mobile, web and (hopefully) desktop builds.
version: 0.1.2
homepage: https://github.com/jhourlad/flutter_session

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
